### ISSUE TITLE
test doesn't display a book out of the box

### ISSUE THREAD

**Issue by holtzermann17** [Vaporbook/epub2web#1]
Cloned the repo and browsed to the test, I don't see an epub, although I do see the beginning of a nice UI.  It would be great to see some actual sample content served from the `epubs` directory.

Example: http://metameso.org/~joe/epub2web/test/testreader.html

**Comment by Vaporbook** [comment]
Hi,
You should be able to test it by running 'npm test' from the project root. It should start the server and give you a URL to view. If that doesnt work, let me know...
Aaron

**Comment by holtzermann17** [comment]
OK, that worked.
